### ISSUE TITLE
MetaFields.java being deleted by the IncrementalBuilder

### ISSUE THREAD

**Issue by minesh-s-patel** [finos/rune-dsl#139]
`MetaFieldGenerator` generates a file called `MetaFields.java` once per rosetta namespace.

Since the generator actually gets called once per resource, an AdapterFactory is used so that it only gets generated once. This however causes an issue with the `IncrementalBuilder` which seems to delete the `MetaFields.java` when using the xtext lsp.

The bug was identified and a workaround was introduced in PR: https://github.com/REGnosys/rosetta-dsl/pull/138.

To reproduce this, re-comment in the code from the PR and run the rosetta grammar in an LSP environment and you will see the `MetaFields.java` being created and then immediately deleted.

**Comment by SimonCockx** [comment]
Fixed by #875
