### ISSUE TITLE
meta reference are not being generated properly 

### ISSUE THREAD

**Issue by PayalKhanna** [finos/rune-dsl#814]
When upgrading an old client model the Classes directory is not generated. 

Static compile error

cannot find symbol

 symbol:  class ReferenceWithMetaIdentifier

 location: package cdm.base.staticdata.identifier.metafields

package cdm.base.staticdata.identifier.metafields.ReferenceWithMetaIdentifier does not exist

package ReferenceWithMetaIdentifier does not exist

package ReferenceWithMetaIdentifier does not exist

**Comment by SimonCockx** [comment]
Actually a duplicate of https://github.com/finos/rune-dsl/issues/812
