### ISSUE TITLE
Shorthand for referencing enum values if enum type can be derived from the context

### ISSUE THREAD

**Issue by SimonCockx** [finos/rune-dsl#820]
Having to write out the enum type name when accessing enum values is verbose, whereas the type name can often be derived from the context. For example, consider the following condition.
```
previousWorkflowStep -> action = ActionEnum -> New
```
Since the left-hand side of this equality expression is of type `ActionEnum`, we know that the right hand side *must* be an `ActionEnum` value as well, so it would be more concise if we could shorten it as
```
previousWorkflowStep -> action = New
```

Other examples where the enum type could be derived instead of stated include:
- When assigning the output of a function if the output is an enum type.
- As an argument to a function which expects an enum type as an input.

## Implementation consequences

The Rune language will provide a service which computes the expected type of an expression, which will be used in the scope provider to automatically make enum values available to reference. Note that the `RosettaEnumValue` will now extend `RosettaSymbol`, since it can be used in an expression as a symbol directly. As a consequence, code generators supporting generation of expressions (Java, Python) should add support for this case when generating a `RosettaSymbolReference`.

**Comment by brianlynn2** [comment]
It would be helpful if in the Rosetta/Rune development environment, it would show (e.g. as a popup/tooltip) the enumeration type corresponding to the enumeration value.  For example, in the given example:

previousWorkflowStep -> action = New

if a user moused over the word "New" in the editor, a tooltip might show "ActionEnum" or "Enumeration:  ActionEnum".

**Comment by SimonCockx** [comment]
Suggestion for including the enum name on hover is included in the PR.
